version: '3.8'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: aoc2021
      POSTGRES_PASSWORD: aoc2021
      POSTGRES_DB: aoc2021
    restart: always  
